# Generated by Django 5.2.9 on 2026-07-15 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['workspace_id', 'user__email'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='workspaces__slug_b5cc60_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_by', 'name'], name='workspaces__created_c6b9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role'], name='workspaces__workspa_0c4683_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user', 'is_active'], name='workspaces__user_id_f1e817_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemembership',
            unique_together={('workspace', 'user')},
        ),
    ]
